2021/01/14 14:41:29 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f12cb9a30f0>: Failed to establish a new connection: [Errno 111] Connection refused',)) : False
2021/01/18 13:04:39 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbd7e0b6128>: Failed to establish a new connection: [Errno 111] Connection refused',)) : False
