2021/01/13 12:33:03 : Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 665, in storage_data
    getattr(self.get_source_cart(), 'finish_storage_data')()
  File "/home/hoang/Desktop/v32/cartmigration/models/basecart.py", line 3929, in finish_storage_data
    folder_upload = self.get_folder_upload(self._migration_id)
  File "/home/hoang/Desktop/v32/cartmigration/models/basecart.py", line 3941, in get_folder_upload
    folder_upload = root_path + '/' + DIR_UPLOAD + '/' + get_config_ini('src', 'file', file = 'test.ini')
TypeError: must be str, not NoneType

2021/01/13 12:40:26 : orders_errors 1: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1256, in convert_order_export
    order_item['product']['id'] = order_product['oders_products_id']
KeyError: 'oders_products_id'

2021/01/13 12:40:26 : orders_errors 2: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1256, in convert_order_export
    order_item['product']['id'] = order_product['oders_products_id']
KeyError: 'oders_products_id'

2021/01/13 12:40:26 : orders_errors 3: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1256, in convert_order_export
    order_item['product']['id'] = order_product['oders_products_id']
KeyError: 'oders_products_id'

2021/01/13 12:40:26 : orders_errors 4: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1256, in convert_order_export
    order_item['product']['id'] = order_product['oders_products_id']
KeyError: 'oders_products_id'

2021/01/13 12:40:30 : orders_errors 5: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1256, in convert_order_export
    order_item['product']['id'] = order_product['oders_products_id']
KeyError: 'oders_products_id'

2021/01/13 12:40:30 : orders_errors 6: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1256, in convert_order_export
    order_item['product']['id'] = order_product['oders_products_id']
KeyError: 'oders_products_id'

2021/01/13 12:40:30 : orders_errors 7: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1256, in convert_order_export
    order_item['product']['id'] = order_product['oders_products_id']
KeyError: 'oders_products_id'

2021/01/13 12:40:30 : orders_errors 8: Traceback (most recent call last):
  File "/home/hoang/Desktop/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/home/hoang/Desktop/v32/cartmigration/models/cart/custom.py", line 1256, in convert_order_export
    order_item['product']['id'] = order_product['oders_products_id']
KeyError: 'oders_products_id'

